/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spreadtrum_android_eng_EngWifieut */

#ifndef _Included_com_spreadtrum_android_eng_EngWifieut
#define _Included_com_spreadtrum_android_eng_EngWifieut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spreadtrum_android_eng_EngWifieut
 * Method:    ptestCw
 * Signature: (Lcom/spreadtrum/android/eng/EngWifieut/ptestCw;)I
 */
JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestCw
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spreadtrum_android_eng_EngWifieut
 * Method:    ptestTx
 * Signature: (Lcom/spreadtrum/android/eng/EngWifieut/PtestTx;)Lcom/spreadtrum/android/eng/EngWifieut/PtestRes;
 */
JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestTx
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spreadtrum_android_eng_EngWifieut
 * Method:    ptestRx
 * Signature: (Lcom/spreadtrum/android/eng/EngWifieut/ptestRx;)I
 */
JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestRx
  (JNIEnv *, jobject, jobject);

JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestInit
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestDeinit
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestSetValue
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestBtStart
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_spreadtrum_android_eng_EngWifieut_ptestBtStop
  (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_spreadtrum_android_eng_EngWifieut_ptestRx */

#ifndef _Included_com_spreadtrum_android_eng_EngWifieut_ptestRx
#define _Included_com_spreadtrum_android_eng_EngWifieut_ptestRx
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_spreadtrum_android_eng_EngWifieut_ptestTx */

#ifndef _Included_com_spreadtrum_android_eng_EngWifieut_ptestTx
#define _Included_com_spreadtrum_android_eng_EngWifieut_ptestTx
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_spreadtrum_android_eng_EngWifieut_ptestCw */

#ifndef _Included_com_spreadtrum_android_eng_EngWifieut_ptestCw
#define _Included_com_spreadtrum_android_eng_EngWifieut_ptestCw
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_spreadtrum_android_eng_EngWifieut_PtestRes */

#ifndef _Included_com_spreadtrum_android_eng_EngWifieut_PtestRes
#define _Included_com_spreadtrum_android_eng_EngWifieut_PtestRes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
